### ISSUE TITLE
(go1.20rc1) reflect: call of reflect.Value.Int on struct Value

### ISSUE THREAD

**Issue by prestonvanloon** [trailofbits/go-mutexasserts#1]
```
--- FAIL: TestRWMutexLocked (0.00s)
panic: reflect: call of reflect.Value.Int on struct Value [recovered]
        panic: reflect: call of reflect.Value.Int on struct Value

goroutine 7 [running]:
testing.tRunner.func1.2({0x50b9a0, 0xc0000100f0})
        /home/preston/sdk/gotip/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /home/preston/sdk/gotip/src/testing/testing.go:1529 +0x39f
panic({0x50b9a0, 0xc0000100f0})
        /home/preston/sdk/gotip/src/runtime/panic.go:884 +0x213
reflect.Value.Int(...)
        /home/preston/sdk/gotip/src/reflect/value.go:1461
github.com/trailofbits/go-mutexasserts.RWMutexRLocked(0xc00004e760?)
        /tmp/go-mutexasserts/mutex.go:22 +0x13d
github.com/trailofbits/go-mutexasserts.TestRWMutexLocked(0xc000007ba0)
        /tmp/go-mutexasserts/asserts_test.go:29 +0x45
testing.tRunner(0xc000007ba0, 0x5355a8)
        /home/preston/sdk/gotip/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /home/preston/sdk/gotip/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/trailofbits/go-mutexasserts  0.004s
FAIL
```

Using gotip version
```
go version devel go1.20-db36eca Thu Dec 29 23:36:05 2022 +0000 linux/amd64
```

To repro, use gotip or go1.20rc1
```
gotip test -tags debug ./...
```

**Comment by prestonvanloon** [comment]
This is due to a recent change where RWMutex switched to atomic.Int32 in commit https://github.com/golang/go/commit/e509452727b469d89a3fc4a7d1cbf9d3f110efee
